### ISSUE TITLE
Determine alignment with ISO mdl

### ISSUE THREAD

**Issue by dif-admin** [decentralized-identity/credential-schemas#1]
We want to investigate alignment with ISO mdl. This involves (at minimum) several steps. This issue can be broken up into separate issues for improved tracking.

- [ ] Get access to ISO mdl
- [ ] Investigate/research differences
- [ ] Alignment proposal
- [ ] Spec updates (if any) and additional guidance

At a conceptual level, here are some differences likely not covered by mdl, based on the use case. So this is related to #2. This is intended only as a starting point.

Not covered by mdl:
1. Comprehensive background checks including credit history & criminal record
2. Address verification: additional proof of address (utility bills, bank statements)
3. Transaction monitoring and behavioral analysis
4. Risk assessment and profiling (based on factors like occupation and geo)
5. Sanctions screenings
6. Enhanced due diligence for high-risk customers

**Comment by kimdhamilton** [comment]
ISO Mdl attributes
```
age_in_years
age_birth year
age_over_NN
issue_date
expiry_date
issuing_country
issuing_authority
document number
administrative_number
driving_privileges
un_distinguishing_sign
issuing _jurisdiction
family_name
given_name
birth_date
gender
birth_place
resident_address
portrait
portrait_capture_date
nationality
resident_city
resident_state
resident_ postal_code
name_national_character
height
weight
eye_color
hair_color
biometric_ template_xx
signature_ usual_mark
online_token_ XXXX
online_url_ XXXX
```

**Comment by ottomorac** [comment]
Wanted to also note other standards mentioned by Adrian during the call (so we can have them here for reference):

- [ISO/IEC TS 29003:2018 - Security techniques — Identity proofing](https://www.iso.org/standard/62290.html)
- [ISO 24366:2021 Financial services — Natural person identifier](https://www.iso.org/standard/78504.html)
- [ICAO Doc 9303 - Machine Readable Travel Documents](https://www.icao.int/publications/pages/publication.aspx?docnum=9303)
- [ISO/IEC DIS 24760-1 - A framework for identity management](https://www.iso.org/standard/87485.html)
- [MyData Dictionary](https://dictionary.mydata.org/)
