### ISSUE TITLE
Find and help VC Issuers develop their schemas

### ISSUE THREAD

**Issue by jimschoening1** [decentralized-identity/credential-schemas#5]
I propose we find VC Issuers using any available tools (e.g. Trinsic) to create real world VCs. To do so requires developing a schema with terms and definitions, which we can offer to help them with, and their feedback will help us understand and meet their needs, automate the help process, develop a good standard, plus initiate early adoption now.  When I used Trinsic a couple years ago, their training materials gave vague guidance on how to select or develop a schema, but I see now they seem to have left this business and are focused on just verification.    But I'm sure other vendors provide tools for organizations to issue VCs. 

Kim replied (in an email to me), "I think we can definitely drum up a few additional issuers: Trinsic, Dock, Cheqd for example are all DIF members. They've all mentioned interest in staying in the loop, so this is perfect."

Please reply with your thoughts on this strategy, plus ideas on how to find such Issuers.

**Comment by kimdhamilton** [comment]
I should clarify -- in my mind this is a nice-to-have for later, but not a primary goal and there's something of more relevance/priority:

Convert the spreadsheet into a "spec" oriented form. Getting it version controlled, in github if at all possible, will be key for the longevity, and IMO will be much more likely to get feedback / viewers from the community (especially in decentralized identity community)

We need to decide which format to use. DIF's default spec format uses spec-up, which ends up looking like this: https://identity.foundation/presentation-exchange/. I'm not sure that's conducive to data model, so we can see if people have other proposals. Some DIF specs use IETF format, and I think we could explore others.

Then we confirm the set of attributes that belong in the KYC schema (the first priority of the schemas) and cut a version of the spec.

**Comment by ottomorac** [comment]
Closing this issue for now. Feel free to re-open if the topic has not been fully addressed.
